### ISSUE TITLE
Is it possible to dag export to car and do stream-commp together?

### ISSUE THREAD

**Issue by kernelogic** [filecoin-project/go-fil-commp-hashhash#10]
For example `ipfs dag export bafybeia6po64b6tfqq73lckadrhpihg2oubaxgqaoushquhcek46y3zumm > 123.car | stream-commp`

**Comment by ribasushi** [comment]
@kernelogic sorry I didn't see this. Use the Unix-Froce, Luke:

`some-process | tee output.file | another-process`
